name = "TypeArrays"
uuid = "bee2e7eb-b2c9-42af-b3cc-072614fb9bfe"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "1.0.0-DEV"

[deps]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"

[compat]
StaticArrays = "1"
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"


[targets]
test = ["Test"]
