name = "TypeArrays"
uuid = "bee2e7eb-b2c9-42af-b3cc-072614fb9bfe"
authors = ["Rafael Schouten <rafaelschouten@gmail.com>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
